-- 실습

-- 테이블 삭제
DROP TABLE MEMBER2;

-- 테이블 만들기
CREATE TABLE MEMBER(
    ID VARCHAR2(100),
    PWD VARCHAR2(100)
);

-- 테이블 조회
SELECT * FROM MEMBER;
SELECT ID,PWD FROM MEMBER;

--데이터 삽입
INSERT INTO MEMBER (ID,PWD) VALUES('USER01','1234');
INSERT INTO MEMBER (ID,PWD) VALUES('USER02','2222');
INSERT INTO MEMBER (ID,PWD) VALUES('USER03','3333');
INSERT INTO MEMBER (ID,PWD) VALUES('USER04','4444');
INSERT INTO MEMBER (ID,PWD) VALUES('USER05','5555');

--테이블 조회(ID 값이 USER01)
SELECT * FROM MEMBERWHERE ID ='USER01' OR PWD = '5555';

--데이터 수정 (비밀번호를 0000으로 변경)
UPDATE MEMBER SET PWD  = '0000'; 

--데이터 수정 (비밀번호를 1234로 변경, USER01 회원만)
UPDATE MEMBER SET PWD  = '1234' WHERE ID='USER01';

--데이터 삭제 (USER01만 삭제)
DELETE MEMBER WHERE ID='USER01';

--데이터 삭제 (모든 행)
DELETE FROM MEMBER;

--테이블 삭제 (테이블)
DROP TABLE MEMBER;

