DROP TABLE NOTICE CASCADE CONSTRAINTS;  
--ALTER TABLE NOTICE DROP CONSTRAINT FK_ADMIN_NOTICE;

CREATE TABLE NOTICE (
	NOTICE_NO	    NUMBER		    PRIMARY KEY
	,ADMIN_NO	    NUMBER		    NOT NULL
	,TITLE	        VARCHAR2(100)
	,CONTENT	    VARCHAR2(2000)
	,INQUIRY	    NUMBER	        DEFAULT 0
	,ENROLL_DATE	TIMESTAMP	    DEFAULT SYSDATE
	,UPDATE_DATE	TIMESTAMP		DEFAULT SYSDATE
	,FIXED_YN	    CHAR(1)	        DEFAULT 'N'
	,DEL_YN	        CHAR(1)	        DEFAULT 'Y'
);

---------------------코멘트--------------------
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지글번호"PK"';
COMMENT ON COLUMN "NOTICE"."ADMIN_NO" IS '작성한 관리자 번호';
COMMENT ON COLUMN "NOTICE"."TITLE" IS '공지사항 제목';
COMMENT ON COLUMN "NOTICE"."CONTENT" IS '공지사항 내용';
COMMENT ON COLUMN "NOTICE"."INQUIRY" IS '조회수';
COMMENT ON COLUMN "NOTICE"."ENROLL_DATE" IS '작성일';
COMMENT ON COLUMN "NOTICE"."UPDATE_DATE" IS '수정일';
COMMENT ON COLUMN "NOTICE"."FIXED_YN" IS '상단 고정 여부';
COMMENT ON COLUMN "NOTICE"."DEL_YN" IS '글 공개 여부';

---------------------시퀀스--------------------
--NOTICE
DROP SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_NOTICE NOCYCLE NOCACHE;
--SEQ_NOTICE.NEXTVAL;

-------------------외래키----------------------
--FK_NOTICE_ADMIN
ALTER TABLE NOTICE ADD CONSTRAINT FK_ADMIN_NOTICE FOREIGN KEY (ADMIN_NO)
REFERENCES ADMIN (ADMIN_NO);

---------------------더미데이터--------------------
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'1','초기 공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
commit;

--테스트용
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (1,'1','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (2,'1','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (3,'2','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (4,'3','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (5,'5','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (6,'4','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (7,'2','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (8,'2','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (9,'1','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (10,'1','공지사항 테스트 입니다.','TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST');
commit;