DROP TABLE CUSTOMER_CENTER CASCADE CONSTRAINTS;  
--ALTER TABLE NOTICE DROP CONSTRAINT FK_ADMIN_NOTICE;
--ALTER TABLE NOTICE DROP CONSTRAINT FK_ADMIN_NOTICE;

CREATE TABLE CUSTOMER_CENTER (
	Q_NO	            NUMBER          PRIMARY KEY
	,ADMIN_NO	        NUMBER
	,MEM_NO	            NUMBER          NOT NULL
	,Q_TIT	            VARCHAR2(100)
	,Q_CON	            VARCHAR2(2000)
	,Q_WRITE_DATE	    TIMESTAMP	    DEFAULT SYSDATE
	,ANSEWR	            VARCHAR2(4000)
	,ANSEWR_DATE	    TIMESTAMP
	,UPDATE_DATE	    TIMESTAMP
	,DEL_YN	            CHAR(1)	        DEFAULT 'N'
	,QUESTION_CATEGORY	CHAR(4)		    NOT NULL
);

---------------------코멘트--------------------
COMMENT ON COLUMN "CUSTOMER_CENTER"."Q_NO" IS '문의글 번호"PK"';
COMMENT ON COLUMN "CUSTOMER_CENTER"."ADMIN_NO" IS '답변 관리자 번호';
COMMENT ON COLUMN "CUSTOMER_CENTER"."MEM_NO" IS '글 작성자 번호';
COMMENT ON COLUMN "CUSTOMER_CENTER"."Q_TIT" IS '문의글 제목';
COMMENT ON COLUMN "CUSTOMER_CENTER"."Q_CON" IS '문의글 내용';
COMMENT ON COLUMN "CUSTOMER_CENTER"."Q_WRITE_DATE" IS '작성일';
COMMENT ON COLUMN "CUSTOMER_CENTER"."ANSEWR" IS '답변 내용';
COMMENT ON COLUMN "CUSTOMER_CENTER"."ANSEWR_DATE" IS '답변 작성일';
COMMENT ON COLUMN "CUSTOMER_CENTER"."UPDATE_DATE" IS '답변 수정일';
COMMENT ON COLUMN "CUSTOMER_CENTER"."DEL_YN" IS '글 공개 여부(삭제여부)';
COMMENT ON COLUMN "CUSTOMER_CENTER"."QUESTION_CATEGORY" IS '문의글 구분(문의/기능신고)';

---------------------시퀀스--------------------
--NOTICE
DROP SEQUENCE SEQ_CUSTOMER_CENTER;
CREATE SEQUENCE SEQ_CUSTOMER_CENTER NOCYCLE NOCACHE;
--SEQ_CUSTOMER_CENTER.NEXTVAL;

-------------------외래키----------------------
--ALTER TABLE CUSTOMER_CENTER ADD CONSTRAINT FK_ADMIN_CUSTOMER_CENTER FOREIGN KEY (ADMIN_NO)
--REFERENCES ADMIN (ADMIN_NO);
--
--ALTER TABLE CUSTOMER_CENTER ADD CONSTRAINT FK_MEMBER_CUSTOMER_CENTER FOREIGN KEY (MEM_NO)
--REFERENCES MEMBER (MEM_NO);

---------------------더미데이터--------------------
INSERT INTO CUSTOMER_CENTER(Q_NO,MEM_NO,Q_TIT,Q_CON,QUESTION_CATEGORY) VALUES 
(SEQ_CUSTOMER_CENTER.NEXTVAL,'1','초기 1:1문의 테스트 입니다.'
,'TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST','NM');
commit;

