--MINI

--테이블 삭제 구문
DROP TABLE MEMBER CASCADE CONSTRAINTS; --제약조건도 같이 삭제
DROP TABLE BOARD CASCADE CONSTRAINTS;  --제약조건도 같이 삭제


--MEMBER
CREATE TABLE MEMBER(
    NO              NUMBER        PRIMARY KEY
    ,ID             VARCHAR2(100) NOT NULL UNIQUE
    ,PWD            VARCHAR2(100) NOT NULL
    ,NICK           VARCHAR2(100) NOT NULL UNIQUE
	,ENROLL_DATE    TIMESTAMP     DEFAULT SYSDATE
	,MODIFY_DATE    TIMESTAMP
	,DEL_YN         CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
);

--BOARD
CREATE TABLE BOARD(
    NO             NUMBER        PRIMARY KEY
    ,TITLE         VARCHAR2(100) NOT NULL
    ,CONTENT       VARCHAR2(800) NOT NULL
    ,WRITER_NO     NUMBER        --외래키는 ALTER 
    ,HIT           NUMBER        DEFAULT  0     --조회수
    ,ENROLL_DATE   TIMESTAMP     DEFAULT SYSDATE
    ,MODIFY_DATE   TIMESTAMP
    ,DEL_YN        CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
    
);

--외래키
ALTER TABLE BOARD 
ADD CONSTRAINT FK_BOARD_MEMBER
FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
----------------------------------------------
--시퀀스 생성
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;
--SEQ_MEMBER.NEXTVAL;

DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCYCLE NOCACHE;
--SEQ_BOARD.NEXTVAL;
-------------------------

--더미데이터
--ADMIN 
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'ADMIN','1234','관리자');

--MEMBER
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER01','1234','NICK01');
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER02','1234','NICK02');
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER03','1234','NICK03');
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER04','1234','NICK04');
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER05','1234','NICK05');
INSERT INTO MEMBER(NO,ID,PWD,NICK) VALUES (SEQ_MEMBER.NEXTVAL,'USER06','1234','NICK06');
COMMIT;

--BOARD
INSERT INTO BOARD (NO,TITLE,CONTENT,WRITER_NO) 
VALUES (SEQ_BOARD.NEXTVAL,'TEST TITLE 01','TEST CONTENT 01',1);
INSERT INTO BOARD (NO,TITLE,CONTENT,WRITER_NO) 
VALUES (SEQ_BOARD.NEXTVAL,'TEST TITLE 02','TEST CONTENT 02',2);
INSERT INTO BOARD (NO,TITLE,CONTENT,WRITER_NO) 
VALUES (SEQ_BOARD.NEXTVAL,'TEST TITLE 03','TEST CONTENT 03',3);
INSERT INTO BOARD (NO,TITLE,CONTENT,WRITER_NO) 
VALUES (SEQ_BOARD.NEXTVAL,'TEST TITLE 04','TEST CONTENT 04',4);
INSERT INTO BOARD (NO,TITLE,CONTENT,WRITER_NO) 
VALUES (SEQ_BOARD.NEXTVAL,'TEST TITLE 05','TEST CONTENT 05',5);
COMMIT;
