-- 마이바티스 수업용 테이블
DROP TABLE BOARD_TEMP CASCADE CONSTRAINTS;
CREATE TABLE BOARD_TEMP(
    TITLE VARCHAR2(1000)
    ,CONTENT VARCHAR2(4000)
    ,ENROLL_DATE TIMESTAMP  DEFAULT SYSDATE
);

SELECT * FROM BOARD_TEMP;

INSERT INTO BOARD_TEMP (TITLE,CONTENT) VALUES ('제목입니다.','내용입니다.');
COMMIT;
ROLLBACK;

-- 마이바티스 연습용 테이블
DROP TABLE MEMBER_TEMP CASCADE CONSTRAINTS;
CREATE TABLE MEMBER_TEMP(
    ID VARCHAR2(1000)
    ,PWD VARCHAR2(4000)
    ,NICK VARCHAR2(4000)
    ,ENROLL_DATE TIMESTAMP  DEFAULT SYSDATE
    ,DEL_YN CHAR(1)  DEFAULT 'N'
    
);

SELECT * FROM MEMBER_TEMP;

INSERT INTO MEMBER_TEMP (ID,PWD,NICK) VALUES ('user','0000','유저');
COMMIT;
ROLLBACK;