DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	ID	VARCHAR2(100)
	,PW	VARCHAR2(100)
	,NICK	VARCHAR2(100)
	,ENROLL_DATE	TIMESTAMP
);

DROP TABLE ITEM;
CREATE TABLE ITEM(
	NAME	VARCHAR2(100)
	,PRICE	NUMBER
	,CNT	NUMBER
	,ENROLL_DATE	TIMESTAMP		
);

--회원가입
INSERT INTO MEMBER(ID,PW,NICK,ENROLL_DATE) VALUES ('아이디','비번','닉네임',SYSDATE);
--로그인
SELECT * FROM MEMBER WHERE ID='아이디' AND PW= '비번';
--비밀번호 변경
UPDATE MEMBER SET PW = '변경할 비번' WHERE ID = '아이디' AND PW = '비번';
--탈퇴
DELETE MEMBER WHERE ID='아이디' AND PW = '비번';
--상품 등록
INSERT INTO ITEM(NAME,PRICE,CNT,ENROLL_DATE) VALUES ('상품명',가격,재고량,SYSDATE) ;
--상품 가격 변동
UPDATE ITEM SET PRICE=변경할_가격 WHERE NAME = '상품명';
--상품 삭제
DELETE ITEM WHERE NAME = '삭제할 상품 이름' ;
--모든 상품 조회 (최신 등록순)
SELECT * FROM ITEM ORDER BY enroll_date DESC;
