--MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    NO              NUMBER          PRIMARY KEY
    ,ID             VARCHAR2(100)   NOT NULL UNIQUE
    ,PWD            VARCHAR2(100)   NOT NULL
    ,NICK           VARCHAR2(100)   NOT NULL
    ,PHONE          CHAR(13)
    ,EMAIL          VARCHAR2(100)
    ,ADDRESS        VARCHAR2(100)
    ,HOBBYS         VARCHAR2(100)
    ,ENROLL_DATE    TIMESTAMP      DEFAULT SYSDATE
    ,MODIFY_DATE    TIMESTAMP      DEFAULT SYSDATE
    ,STATUS         CHAR(1)        DEFAULT 'O'      CHECK (STATUS IN ('O' , 'X'))
);
--INSERT INTO MEMBER (NO,ID,PWD,PHONE,EMAIL,ADDRESS,HOBBYS) 
--VALUES (SEQ_MEMBER_NO,'','','','','','');
--DROP TABLE BOARD;
