--외래키 지우기
ALTER TABLE BOARD DROP CONSTRAINT FK_BOARD_MEMBER;
ALTER TABLE BOARD DROP CONSTRAINT FK_BOARD_CATEGORY;
commit;

--MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE; --SEQ_MEMBER_NO.NEXTVAL
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    NO              NUMBER          PRIMARY KEY
    ,ID             VARCHAR2(100)   NOT NULL UNIQUE
    ,PWD            VARCHAR2(100)   NOT NULL
    ,NICK           VARCHAR2(100)   NOT NULL
    ,PHONE          CHAR(13)
    ,EMAIL          VARCHAR2(100)
    ,ADDRESS        VARCHAR2(100)
    ,HOBBYS         VARCHAR2(100)
    ,ENROLL_DATE    TIMESTAMP      DEFAULT SYSDATE
    ,MODIFY_DATE    TIMESTAMP      DEFAULT SYSDATE
    ,STATUS         CHAR(1)        DEFAULT 'O'      CHECK (STATUS IN ('O' , 'X'))
);
--BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE; --SEQ_BOARD_NO.NEXTVAL
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    ,CATEGORY_NO    NUMBER          NOT NULL
    ,TITLE          VARCHAR2(100)   NOT NULL
    ,CONTENT        VARCHAR2(4000)  NOT NULL
    ,WRITER_NO      NUMBER          NOT NULL
    ,HIT            NUMBER          DEFAULT 0
    ,ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
    ,MODIFY_DATE    TIMESTAMP       DEFAULT SYSDATE
    ,STATUS         CHAR(1)         DEFAULT 'O' CHECK (STATUS IN ('O','X'))
);
--CATAGORY
DROP TABLE CATEGORY;
CREATE TABLE CATEGORY(
    NO              NUMBER          PRIMARY KEY
    ,NAME           VARCHAR2(100)   NOT NULL
);
--외래키

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);

--데이터 (MEMBER)
INSERT INTO MEMBER (NO,ID,PWD,NICK) VALUES (0,'admin','1234','관리자');
commit;

--데이터 (CATEGORY)
INSERT INTO CATEGORY (NO, NAME) VALUES (1,'자유');
INSERT INTO CATEGORY (NO, NAME) VALUES (2,'게임');
INSERT INTO CATEGORY (NO, NAME) VALUES (3,'요리');
INSERT INTO CATEGORY (NO, NAME) VALUES (4,'운동');
INSERT INTO CATEGORY (NO, NAME) VALUES (5,'자바');
INSERT INTO CATEGORY (NO, NAME) VALUES (6,'자바스크립트');
INSERT INTO CATEGORY (NO, NAME) VALUES (7,'쿼리');
INSERT INTO CATEGORY (NO, NAME) VALUES (8,'기타');
commit;

--데이터(BOAED)
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,1,'제목01','내용01',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,5,'제목02','내용02',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목03','내용03',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목04','내용04',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목05','내용05',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목06','내용06',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목07','내용07',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목08','내용08',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목09','내용09',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목10','내용10',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목11','내용11',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목12','내용12',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목13','내용13',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목14','내용14',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목15','내용15',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목16','내용16',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목17','내용17',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목18','내용18',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목19','내용19',0);
INSERT INTO BOARD (NO,CATEGORY_NO,TITLE,CONTENT,WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL,7,'제목20','내용20',0);

commit;
