-- 사용자 계정 생성 (관리자 계정으로 만 가능)
-- [문법]
-- CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##SEMI IDENTIFIED BY 1234;

-- 권한 부여
-- [문법]
-- GRANT 권한1, 권한2, 
GRANT CONNECT , RESOURCE TO C##SEMI;

ALTER USER C##SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;