-- BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO                  NUMBER          PRIMARY KEY
    , TITLE             VARCHAR2(100)   NOT NULL
    , CONTENT           VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
);
INSERT INTO BOARD (NO,TITLE,CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL,'테스트 제목입니다.01','테스트 내용입니다.01');
SELECT * FROM BOARD;
ROLLBACK;