--더미데이터 

--AREAS (동네코드)
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'신사동');--1
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'논현동');--2
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'압구정동');--3
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'청담동');--4
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'삼성동');--5
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'대치동');--6
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'일원동');--7
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'역삼동');--8
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'개포동');--9
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'세곡동');--10
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'수서동');--11
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'율현동');--12
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'자곡동');--13
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'도곡동');--14

COMMIT;

--MANAGER (관리자)
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN01','1234','관리자');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN02','1234','관리자');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN03','1234','관리자');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN04','1234','관리자');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN05','1234','관리자');
COMMIT;

--MEMBER ( 사용자)
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER01','1234','새벽갬성','양주은','KH01@KH.COM','01000000000','서울시강남구역삼동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER02','1234','보마휘바','남이나','KH02@KH.COM','01011111111','서울시강남구논현동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'10','USER03','1234','후바후바','김광푸','KH03@KH.COM','01022222222','서울시강남구세곡동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'1','USER04','1234','난앓아요','이민진','KH04@KH.COM','01033333333','서울시강남구신사동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'5','USER05','1234','빛과송금','최재영','KH05@KH.COM','01044444444','서울시강남구삼성동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'9','USER06','1234','히히잉힝','하지숙','KH06@KH.COM','01055555555','서울시강남구개포동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'6','USER07','1234','쾌변춘향','이현문','KH07@KH.COM','01066666666','서울시강남구대치동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS,QUIT_YN) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER08','1234','공익인간','김재우','KH08@KH.COM','01077777777','서울시강남구역삼동','Y');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'4','USER09','1234','조던사줘','한민국','KH09@KH.COM','01088888888','서울시강남구청담동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'5','USER10','1234','무크노크','하나리','KH10@KH.COM','01099999999','서울시강남구삼성동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'6','USER11','1234','으른이날','고우람','KH11@KH.COM','01012121212','서울시강남구대치동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS,QUIT_YN) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER12','1234','홍삼보이','유이슬','KH12@KH.COM','01013131313','서울시강남구논현동','Y');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'7','USER13','1234','동네엉아','노미르','KH13@KH.COM','01014141414','서울시강남구일원동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'9','USER14','1234','흑마늘파','김은진','KH14KH.COM','01015151515','서울시강남구개포동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS,QUIT_YN) VALUES (SEQ_MEMBER.NEXTVAL,'11','USER15','1234','커밋푸쉬','홍보라','KH15KH.COM','01016161616','서울시강남구수서동','Y');
COMMIT;

--NOTICE (공지사항) 현묵님
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓을 소개합니다','<Cherry마켓 >은 중고거래 플랫폼입니다. 물품의 재활용을 촉진 소비를 장려하는 역할을 합니다 회원분들의 편의를 위해 노력하는 Cherry마켓이 되겠습니다. 많은 이용 부탁드립니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 개인정보처리','모든 회원분들의 개인정보는 안전하게 저장되고 {휴대전화번호, 주민등록번호, 이메일(등록되어있을 시)},  탈퇴 시 1년 후 개인정보가 삭제됩니다. 이 점 이용에 참고 부탁드립니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 휴먼계정 공지','저희 Cherry마켓은 회원님들의 소중한 개인정보 보호를 위하여 정보통신망 이용촉진 및 정보보호 등에 관한 법률에 따라 최근 1년 동안 이용 기록이 없는 회원은 휴면상태로 전환 됩니다');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'담배 거래시 계정 영구정지','저희 Cherry마켓은 전체 이용가이기 때문에 미성년자분들도 거래를 할 수 있어 담배(전자담배용품),주류등은 19세미만 판매 물품은 거래하실 수 없습니다.이 점 이용에 참고 부탁드립니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 운영 종료 안내','안녕하세요 Cherry마켓입니다.지금까지 저희 Cherry마켓을 이용해 주서셔 감사합니다 보다 나은 서비스를 위해 Cherry마켓시즌2로 찾아 뵙겠습니다 이용에 불편을 드려 죄송합니다.');

--FAQ 광포님
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '회원가입은 어떻게 하나요?', '프로그램 시작 -> 유저 -> 회원가입  순서로 진행하시면 됩니다.');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '비밀번호를 찾고 싶어요!', '프로그램 시작 -> 유저 -> 비밀번호 찾기 순서로 진행하시면 됩니다.');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '글 수정은 어떻게 하나요?', '프로그램 시작 -> 유저 -> 로그인 -> 원하는 게시판 -> 게시판 수정 순서로 진행하시면 됩니다.');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '관심목록을 확인하고 싶어요', '프로그램 시작 -> 유저 -> 로그인 -> 마이페이지 -> 관심목록 조회 순서로 진행하시면 됩니다.');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '매너온도는 어디서 확인하나요', '프로그램 시작 -> 유저 -> 로그인 -> 마이페이지 -> 매너온도 순서로 진행하시면 됩니다.');


--QNA (유저가 작성한 질문글)
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 5, '게시글 개수에 제한이 있나요?', '판매하고 싶은 제품이 많은데 게시글을 몇개 작성할 수 있는지 궁금합니다.');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 3, '택배 거래도 가능한가요?', '판매자가 회사에 판매물품을 두고와서 직거래가 어렵다고 택배로 거래하자는데 가능할까요?');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 7, '내 게시글이 안보여요.', '판매글을 작성했는데 게시글이 안보입니다.');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT, SECRET_YN) VALUES(SEQ_QNA_NO.NEXTVAL, 1, '매너온도를 올리고 싶어요!!', '매너온도가 떨어져서 올리고 싶은데 어떻게 해야할까요?', 'Y');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT, SECRET_YN) VALUES(SEQ_QNA_NO.NEXTVAL, 3, '코스튬 판매글이 삭제됐어요.', '할로윈 코스튬으로 경찰복을 판매하는 게시글이 삭제 됐는데 왜그런가요??', 'Y');

--QNA (관리자가 작성한 답글)
UPDATE QNA SET ANSWER = '하루에 20개의 게시글을 작성 할 수 있고, 한 사람당 300개의 게시글을 작성할 수 있습니다.' WHERE QNA_NO = 1;
UPDATE QNA SET ANSWER = '중복게시글을 작성하셨거나 전문판매없자 제재를 받은 경우 게시글이 안보일 수 있습니다.' WHERE QNA_NO = 3;
UPDATE QNA SET ANSWER = '경찰제복장비법 9조에 따라 경찰제복?장비와 유사경찰제복?장비 제조?판매?대여 금지 및 판매 대여 목적 소지금지로 거래가 불가능한 제품이라 글이 삭제된 것입니다.' WHERE QNA_NO = 5;
COMMIT;

--TRADE
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 9, '바람막이 팝니다', '역삼역', '사이즈는 95, m 사이즈구요 하자 없습니다. 급하게 #처리하는거라 역삼으로 오시면 4만원에 판매하겠습니다', '의류', 50000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 2, 3, '샤오미 전기자전거 팔아요', '도곡 근처', '안장교체(장시간 타도 괜찮음), 그립교체(브룩스 에로고#노믹, 검정색), 추가배터리, 충전선 있고요 그냥 자전#거 값만 받고 판매합니다. 밖에 세워뒀을때 필요한 자전#거 커버도 같이 드릴게요', '자전거', 1000000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 3, 1, 'R2 텐트 팝니다', '강남역4번출구', '2022년 9월에 구매 후 2회 피칭한 듀랑고 R2 판#매합니다. 구성품은 텐트,그라운드시트 대용 방수포 상태# 너무 좋은데 아주 작은 불빵 하나 있어서 저렴하게 팝#니다. 봄가을겨울 사용하기 좋구여 여름도 굿굿 부피가 #있어 직거래 원합니다.', '생활용품', 700000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 4, 10, '에어팟 팝니다', '수서역', '에어팟 프로(Apple AirPods# Pro)는 애플이 제조한 무선 이어#폰으로, 2019년에 출시되었습니다.# 에어팟 프로는 기존의 에어팟과 비교#해 높은 음질, 주변 소음 차단, 햅#틱 터치 컨트롤, 그리고 물리적으로 #귀에 더 잘 맞는 디자인을 특징으로 #합니다.', '에어팟프로', 50000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 5, 14, '김치 팝니다', '우리집', '김치는 대표적인 한국 요리로서 발효된# 양배추나 다른 채소를 주로 고추가루#와 다양한 조미료와 함께 발효시켜 만#든 발효 식품입니다. 김치는 한국 요#리의 중요한 부분이며 한국의 식탁에서# 빠질 수 없는 음식 중 하나입니다.#', '김치', 5000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 6, 1, '포천 펜션 양도해요', '인터넷', '포천에 위치한 독채펜션입니다. 일정이 변경되어 부득이하#게 양도합니다 11월10일~11월11일 1박 기준인원 #4명, 추가인원시 금액 발생합니다. 총 10명까지 숙박# 가능하고 방3개 앞에 바베큐 시설도 있어요. 예약했던# 금액은 50만원입니다.', '티켓', 350000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 7, 4, '맥북프로 M1 14인치', '세곡동', '맥북프로 14인치 M1 (21년형) SSD 500 RA#M 16기가 배터리 사이클수 26, 스페이스 그레이 색#상입니다 깨끗하게 사용했고 애케플 가입되있어요. 필요하#시면 사용했던 애플 멀티포트 어댑터 같이 드릴게요 쿨거#래시 10만원 네고해드립니다!', '맥북', 1900000);
COMMIT;

--WISHLIST - 더미데이터 삭제 요망
--PURCHASE_HISTORY - 더미데이터 삭제 요망
--REVIEW (맨 밑으로 빼기) - 더미 삭제점 ㅎ
--TOWN (동네생활)
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,1,'강아지를 찾습니다.','보시면 연락 주세요..ㅜ','자유');
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,2,'지갑 찾아가세요. ','공원에서 지갑주웠습니다!','자유' );
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,3,'단기알바 구합니다.','하루4시간하실분찾아요..', '알바');
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,2,'붕어빵 찾아요!!! ','역삼동 붕어빵 어디있나요?', '맛집');
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,1,'카페 추천해주세요.','역삼역 근처 추천해주세요.', '자유');


--TOWN_COMMENT (동네생활 댓글)
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 1,2,'저희 강아지 같아요ㅜㅜ');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 2,3,'어디로 가면 될까요!!!!');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 3,1,'시급은 얼마인가요???');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 4,3,'3번 출구 앞에 있어요.');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 5,2,'3번 출구쪽 투썸 있어요!');
