/* 
 *  
 *  
 *  
 *  
 */
 
 --테이블 삭제 구문
DROP TABLE MEMBER CASCADE CONSTRAINTS;          --MEMBER
DROP TABLE AREAS CASCADE CONSTRAINTS;           --AREAS
DROP TABLE MANAGER CASCADE CONSTRAINTS;         --MENAGER
DROP TABLE NOTICE CASCADE CONSTRAINTS;          --NOTICE
DROP TABLE FAQ CASCADE CONSTRAINTS;             --FAQ
DROP TABLE QNA CASCADE CONSTRAINTS;             --QNA
DROP TABLE TRADE CASCADE CONSTRAINTS;           --TRADE
DROP TABLE REVIEW CASCADE CONSTRAINTS;          --REVIEW
DROP TABLE WISHLIST CASCADE CONSTRAINTS;        --WISHLIST
DROP TABLE PURCHASE_HISTORY CASCADE CONSTRAINTS;--PURCHASE_HISTORY
DROP TABLE TOWN CASCADE CONSTRAINTS;            --TOWN
DROP TABLE TOWN_COMMENT CASCADE CONSTRAINTS;    --TOWN_COMMENT

---------------------MEMBER---------------------
CREATE TABLE MEMBER (
	 MEMBER_NO	    NUMBER		        PRIMARY KEY
	,AREAS_CODE	    NUMBER		        NOT NULL
	,ID	            VARCHAR2(100)		NOT NULL    UNIQUE
	,PWD	        VARCHAR2(100)		NOT NULL
	,NICK	        VARCHAR2(100)		NOT NULL    UNIQUE  
	,NAME	        VARCHAR2(50)		NOT NULL   
	,EMAIL 	        VARCHAR2(100)		NOT NULL    UNIQUE
	,PHONE	        CHAR(11)		    NOT NULL    UNIQUE
	,ADDRESS	    VARCHAR2(100)		NOT NULL
	,JOIN_DATE	    TIMESTAMP	        DEFAULT SYSDATE
	,EDIT_DATE	    TIMESTAMP		    
	,QUIT_YN	    CHAR(1)	            DEFAULT 'N'	CHECK(QUIT_YN IN ('Y','N'))
);
---------------------코멘트--------------------
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '사용자번호';
COMMENT ON COLUMN "MEMBER"."AREAS_CODE" IS '동네번호';
COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';
COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."NICK" IS '닉네임';
COMMENT ON COLUMN "MEMBER"."NAME" IS '사용자명';
COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."JOIN_DATE" IS '가입일자';
COMMENT ON COLUMN "MEMBER"."EDIT_DATE" IS '마지막수정일자';
COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '탈퇴여부';

---------------------AREAS---------------------
CREATE TABLE AREAS (
	 AREAS_CODE	    NUMBER		 PRIMARY KEY
	,AREAS_NAME	    VARCHAR2(100) NOT NULL
);
---------------------코멘트--------------------
COMMENT ON COLUMN "AREAS"."AREAS_CODE" IS '동네번호';
COMMENT ON COLUMN "AREAS"."AREAS_NAME" IS '동네이름';

---------------------MANAGER---------------------
CREATE TABLE MANAGER (
	MANAGER_NO	    NUMBER		    PRIMARY KEY
	,MANAGER_ID	    VARCHAR2(100)	NOT NULL    UNIQUE
	,PWD	        VARCHAR2(100)	NOT NULL
	,NAME	        VARCHAR2(100)	NOT NULL
	,JOIN_DATE	    TIMESTAMP	    DEFAULT SYSDATE
	,QUIT_YN	    CHAR(1)	        DEFAULT 'N' CHECK(QUIT_YN IN ('Y','N')) 
);
---------------------코멘트--------------------
COMMENT ON COLUMN "MANAGER"."MANAGER_NO" IS '관리자번호';
COMMENT ON COLUMN "MANAGER"."MANAGER_ID" IS '관리자아이디';
COMMENT ON COLUMN "MANAGER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MANAGER"."NAME" IS '관리자명';
COMMENT ON COLUMN "MANAGER"."JOIN_DATE" IS '가입일자';
COMMENT ON COLUMN "MANAGER"."QUIT_YN" IS '탈퇴여부';

---------------------NOTICE---------------------
CREATE TABLE NOTICE (
	 NOTICE_NO	    NUMBER		        PRIMARY KEY
	,MANAGER_NO	    NUMBER		        NOT NULL
	,TITLE	        VARCHAR2(1000)		NOT NULL
	,CONTENT	    VARCHAR2(4000)		NOT NULL
	,ENROLL_DATE	TIMESTAMP	        DEFAULT SYSDATE
	,SECRET_YN	    CHAR(1)	            DEFAULT 'N'	 CHECK(SECRET_YN IN('Y','N')) 
	,EDIT_DATE	    TIMESTAMP
    ,HIT            NUMBER              DEFAULT 0
);
---------------------코멘트--------------------
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '게시글번호';
COMMENT ON COLUMN "NOTICE"."MANAGER_NO" IS '작성자번호';
COMMENT ON COLUMN "NOTICE"."TITLE" IS '제목';
COMMENT ON COLUMN "NOTICE"."CONTENT" IS '내용';
COMMENT ON COLUMN "NOTICE"."ENROLL_DATE" IS '작성일';
COMMENT ON COLUMN "NOTICE"."SECRET_YN" IS '공개여부';
COMMENT ON COLUMN "NOTICE"."EDIT_DATE" IS '마지막수정일자';
COMMENT ON COLUMN "NOTICE"."HIT" IS '조회수';

---------------------FAQ---------------------
CREATE TABLE FAQ (
	 FAQ_NO	        NUMBER		    PRIMARY KEY
	,MANAGER_NO	    NUMBER		    NOT NULL
	,TITLE	        VARCHAR2(100)	NOT NULL
    ,CONTENT	    VARCHAR2(4000)	NOT NULL
	,ENROLL_DATE	TIMESTAMP	    DEFAULT SYSDATE
    ,SECRET_YN	    CHAR(1)	        DEFAULT 'N'  CHECK(SECRET_YN IN('Y', 'N'))
    ,EDIT_DATE	    TIMESTAMP
    ,HIT            NUMBER          DEFAULT 0
);
---------------------코멘트--------------------
COMMENT ON COLUMN "FAQ"."FAQ_NO" IS '질문번호';
COMMENT ON COLUMN "FAQ"."MANAGER_NO" IS '관리자번호';
COMMENT ON COLUMN "FAQ"."TITLE" IS '질문제목';
COMMENT ON COLUMN "FAQ"."CONTENT" IS '질문내용';
COMMENT ON COLUMN "FAQ"."ENROLL_DATE" IS '게시글작성일';
COMMENT ON COLUMN "FAQ"."SECRET_YN" IS '공개여부';
COMMENT ON COLUMN "FAQ"."EDIT_DATE" IS '마지막수정일자';
COMMENT ON COLUMN "FAQ"."HIT" IS '조회수';

---------------------QNA---------------------
CREATE TABLE QNA (
      QNA_NO                NUMBER              PRIMARY KEY         
    , MEMBER_NO             NUMBER             
    , MANAGER_NO            NUMBER              
    , TITLE                 VARCHAR2(1000)      NOT NULL
    , CONTENT               VARCHAR2(4000)      NOT NULL
    , HIT                   NUMBER              DEFAULT 0
    , MEMBER_ENROLL_DATE    TIMESTAMP           DEFAULT SYSDATE
    , SECRET_YN             CHAR(1)             DEFAULT 'N' CHECK(SECRET_YN IN('Y', 'N'))
    , ANSWER                VARCHAR2(4000)
    , MANAGER_ENROLL_DATE   TIMESTAMP           DEFAULT SYSDATE
    , MANAGER_EDIT_DATE     TIMESTAMP           DEFAULT SYSDATE
);
---------------------코멘트--------------------
COMMENT ON COLUMN "QNA"."QNA_NO" IS '게시글번호';
COMMENT ON COLUMN "QNA"."MEMBER_NO" IS '사용자번호';
COMMENT ON COLUMN "QNA"."MANAGER_NO" IS '관리자번호';
COMMENT ON COLUMN "QNA"."TITLE" IS '제목';
COMMENT ON COLUMN "QNA"."CONTENT" IS '내용';
COMMENT ON COLUMN "QNA"."HIT" IS '조회수';
COMMENT ON COLUMN "QNA"."MEMBER_ENROLL_DATE" IS '사용자의 게시글작성일';
COMMENT ON COLUMN "QNA"."SECRET_YN" IS '공개여부';
COMMENT ON COLUMN "QNA"."ANSWER" IS '관리자의 답변';
COMMENT ON COLUMN "QNA"."MANAGER_ENROLL_DATE" IS '관리자의 답변 작성일';
COMMENT ON COLUMN "QNA"."MANAGER_EDIT_DATE" IS '관리자 답변 수정 일자';

---------------------TRADE---------------------
CREATE TABLE TRADE (
    BOARD_NO	        NUMBER		        PRIMARY KEY
	,MEMBER_NO	        NUMBER		        NOT NULL
	,AREAS_CODE	        NUMBER		        NOT NULL
	,TITLE	            VARCHAR2(100)		NOT NULL
	,TRADE_AREAS	    VARCHAR2(100)		NOT NULL
	,CONTENT	        VARCHAR2(4000)		NOT NULL
	,COMPLETE_YN	    CHAR(1)	            DEFAULT 'N'	CHECK(COMPLETE_YN IN('Y', 'N'))
	,DEL_YN	            CHAR(1)         	DEFAULT 'N'	CHECK(DEL_YN IN('Y', 'N'))
	,PRODUCT	        VARCHAR2(100)		NOT NULL
	,PRICE	            NUMBER		        NOT NULL
	,ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE
	,EDIT_DATE	        TIMESTAMP
    ,HIT                NUMBER              DEFAULT 0
);
---------------------코멘트--------------------
COMMENT ON COLUMN "TRADE"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "TRADE"."MEMBER_NO" IS '작성자 번호';
COMMENT ON COLUMN "TRADE"."AREAS_CODE" IS '동네 코드';
COMMENT ON COLUMN "TRADE"."TITLE" IS '제목';
COMMENT ON COLUMN "TRADE"."TRADE_AREAS" IS '거래 장소';
COMMENT ON COLUMN "TRADE"."CONTENT" IS '내용';
COMMENT ON COLUMN "TRADE"."COMPLETE_YN" IS '거래 상태';
COMMENT ON COLUMN "TRADE"."DEL_YN" IS '게시글 삭제 여부';
COMMENT ON COLUMN "TRADE"."PRODUCT" IS '상품명';
COMMENT ON COLUMN "TRADE"."PRICE" IS '가격';
COMMENT ON COLUMN "TRADE"."ENROLL_DATE" IS '작성일';
COMMENT ON COLUMN "TRADE"."EDIT_DATE" IS '마지막 수정일자';
COMMENT ON COLUMN "TRADE"."HIT" IS '조회수';

---------------------REVIEW---------------------
CREATE TABLE REVIEW (
	 REVIEW_NO	    NUMBER		        PRIMARY KEY
	,PURCHASE_NO	NUMBER		        NOT NULL UNIQUE
	,SCORE	        NUMBER		        NOT NULL
	,CONTENT	    VARCHAR2(100)		NOT NULL
	,ENROLL_DATE	TIMESTAMP	        DEFAULT SYSDATE
);
---------------------코멘트--------------------
COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '후기 번호';
COMMENT ON COLUMN "REVIEW"."PURCHASE_NO" IS '구매내역 번호';
COMMENT ON COLUMN "REVIEW"."SCORE" IS '매너온도 평가';
COMMENT ON COLUMN "REVIEW"."CONTENT" IS '내용';
COMMENT ON COLUMN "REVIEW"."ENROLL_DATE" IS '작성일';

---------------------WISHLIST---------------------
CREATE TABLE WISHLIST (
	 WISHLIST_NO	NUMBER		PRIMARY KEY
	,BOARD_NO	    NUMBER		NOT NULL
	,MEMBER_NO	    NUMBER		NOT NULL
    ,CONSTRAINT UNIQUE_WISHLIST UNIQUE(MEMBER_NO, BOARD_NO)
);
---------------------코멘트--------------------
COMMENT ON COLUMN "WISHLIST"."WISHLIST_NO" IS '관심목록번호';
COMMENT ON COLUMN "WISHLIST"."BOARD_NO" IS '게시글번호';
COMMENT ON COLUMN "WISHLIST"."MEMBER_NO" IS '유저번호';

---------------------PURCHASE_HISTORY---------------------
CREATE TABLE PURCHASE_HISTORY (
	 PURCHASE_NO	NUMBER		PRIMARY KEY
	,BUYER_NO	    NUMBER		NOT NULL
	,BOARD_NO	    NUMBER		NOT NULL
	,ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE
);
---------------------코멘트--------------------
COMMENT ON COLUMN "PURCHASE_HISTORY"."PURCHASE_NO" IS '구매내역번호';
COMMENT ON COLUMN "PURCHASE_HISTORY"."BUYER_NO" IS '구매자';
COMMENT ON COLUMN "PURCHASE_HISTORY"."BOARD_NO" IS '구매한 게시글 번호';
COMMENT ON COLUMN "PURCHASE_HISTORY"."ENROLL_DATE" IS '구매일시';

---------------------TOWN---------------------
CREATE TABLE TOWN(
	  TOWN_NO		NUMBER		    PRIMARY KEY
	, MEMBER_NO	    NUMBER		    NOT NULL
	, TITLE		    VARCHAR2(100)	NOT NULL
	, CONTENT	    VARCHAR2(1000) 	NOT NULL
	, ENROLL_DATE	TIMESTAMP	    DEFAULT SYSDATE
	, DELETE_YN	    CHAR(1)		    DEFAULT 'N'	CHECK(DELETE_YN IN('Y', 'N'))
	, EDIT_DATE	    TIMESTAMP       
	, CATEGORY	    VARCHAR2(100)	NOT NULL
    , HIT           NUMBER          DEFAULT 0
);
---------------------코멘트--------------------
COMMENT ON COLUMN "TOWN"."TOWN_NO" IS '게시판번호';
COMMENT ON COLUMN "TOWN"."MEMBER_NO" IS '사용자번호';
COMMENT ON COLUMN "TOWN"."TITLE" IS '제목';
COMMENT ON COLUMN "TOWN"."CONTENT" IS '내용';
COMMENT ON COLUMN "TOWN"."ENROLL_DATE" IS '작성일';
COMMENT ON COLUMN "TOWN"."DELETE_YN" IS '삭제여부';
COMMENT ON COLUMN "TOWN"."EDIT_DATE" IS '마지막수정일자';
COMMENT ON COLUMN "TOWN"."CATEGORY" IS '카테고리';
COMMENT ON COLUMN "TOWN"."HIT" IS '조회수';

---------------------TOWN_COMMENT---------------------
CREATE TABLE TOWN_COMMENT(
	  COMMENT_NO	NUMBER		    PRIMARY KEY
	, TOWN_NO	    NUMBER		    NOT NULL
	, MEMBER_NO	    NUMBER		    NOT NULL
	, ENROLL_DATE 	TIMESTAMP	    DEFAULT SYSDATE
	, CONTENT	    VARCHAR2(100)	NOT NULL
);

---------------------코멘트--------------------
COMMENT ON COLUMN "TOWN_COMMENT"."COMMENT_NO" IS '댓글번호';
COMMENT ON COLUMN "TOWN_COMMENT"."TOWN_NO" IS '게시글번호';
COMMENT ON COLUMN "TOWN_COMMENT"."MEMBER_NO" IS '작성자번호';
COMMENT ON COLUMN "TOWN_COMMENT"."ENROLL_DATE" IS '작성일';
COMMENT ON COLUMN "TOWN_COMMENT"."CONTENT" IS '댓글내용';



---------------------시퀀스--------------------
--MEMBER
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;
--SEQ_MEMBER.NEXTVAL;

--AREAS
DROP SEQUENCE SEQ_AREAS;
CREATE SEQUENCE SEQ_AREAS NOCYCLE NOCACHE;
--SEQ_AREAS.NEXTVAL;

--MANAGER
DROP SEQUENCE SEQ_MANAGER;
CREATE SEQUENCE SEQ_MANAGER NOCYCLE NOCACHE;
--SEQ_MANAGER.NEXTVAL;

--NOTICE
DROP SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_NOTICE_NO NOCYCLE NOCACHE;


--FAQ
DROP SEQUENCE SEQ_FAQ_NO;
CREATE SEQUENCE SEQ_FAQ_NO NOCYCLE NOCACHE;

--QNA
DROP SEQUENCE SEQ_QNA_NO;
CREATE SEQUENCE SEQ_QNA_NO NOCYCLE NOCACHE;

--BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

--REVIEW
DROP SEQUENCE SEQ_REVIEW_NO;
CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE NOCYCLE;

--WISHLIST
DROP SEQUENCE SEQ_WISHLIST_NO;
CREATE SEQUENCE SEQ_WISHLIST_NO NOCACHE NOCYCLE;

--PURCHASE
DROP SEQUENCE SEQ_PURCHASE_NO;
CREATE SEQUENCE SEQ_PURCHASE_NO NOCACHE NOCYCLE;

--TOWN
DROP SEQUENCE SEQ_TOWN_NO;
DROP SEQUENCE SEQ_TOWN_COMMENT_NO;
--TOWN
CREATE SEQUENCE SEQ_TOWN_NO NOCYCLE NOCACHE ;
CREATE SEQUENCE SEQ_TOWN_COMMENT_NO NOCYCLE NOCACHE ;

-------------------외래키----------------------
--FK_MEMBER
ALTER TABLE MEMBER 
ADD CONSTRAINT FK_MEMBER
FOREIGN KEY (AREAS_CODE) REFERENCES AREAS(AREAS_CODE);

--FK_NOTICE
ALTER TABLE NOTICE 
ADD CONSTRAINT FK_NOTICE 
FOREIGN KEY(MANAGER_NO)REFERENCES MANAGER(MANAGER_NO);

--FK_QNA
ALTER TABLE QNA
ADD CONSTRAINT FK_QNA1 
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO);

--FK_QNA
ALTER TABLE QNA
ADD CONSTRAINT FK_QNA2
FOREIGN KEY(MANAGER_NO) REFERENCES MANAGER (MANAGER_NO);

-- FK_TRADE
ALTER TABLE TRADE 
ADD CONSTRAINT FK_TRADE1
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

--FK_TRADE
ALTER TABLE TRADE
ADD CONSTRAINT FK_TRADE2
FOREIGN KEY (AREAS_CODE)
REFERENCES AREAS (AREAS_CODE);

--FK_REVIEW
ALTER TABLE REVIEW 
ADD CONSTRAINT FK_REVIEW 
FOREIGN KEY (PURCHASE_NO)
REFERENCES PURCHASE_HISTORY (PURCHASE_NO);

--FK_WISHLIST
ALTER TABLE WISHLIST 
ADD CONSTRAINT FK_WISHLIST1 
FOREIGN KEY (BOARD_NO)
REFERENCES TRADE (BOARD_NO);

--FK_WISHLIST
ALTER TABLE WISHLIST 
ADD CONSTRAINT FK_WISHLIST2 
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

--FK_HISTORY
ALTER TABLE PURCHASE_HISTORY 
ADD CONSTRAINT FK_HISTORY1 
FOREIGN KEY (BUYER_NO)
REFERENCES MEMBER (MEMBER_NO);

-- FK_HISTORY 
ALTER TABLE PURCHASE_HISTORY 
ADD CONSTRAINT FK_HISTORY2 
FOREIGN KEY (BOARD_NO)
REFERENCES TRADE (BOARD_NO);

--FK_TOWN
ALTER TABLE TOWN 
ADD CONSTRAINT FK_TOWN
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO); 

--FK_COMMENT
ALTER TABLE TOWN_COMMENT 
ADD CONSTRAINT FK_COMMENT1 
FOREIGN KEY (TOWN_NO)
REFERENCES TOWN (TOWN_NO);

--FK_COMMENT
ALTER TABLE TOWN_COMMENT 
ADD CONSTRAINT FK_COMMENT2
FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

--더미데이터 

--AREAS (동네코드)
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'신사동');--1
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'논현동');--2
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'압구정동');--3
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'청담동');--4
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'삼성동');--5
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'대치동');--6
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'삼성동');--7
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'역삼동');--8
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'개포동');--9
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'세곡동');--10
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'수서동');--11
COMMIT;

--MANAGER (관리자)
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN01','1234','관리자01');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN02','1234','관리자02');
COMMIT;

--MEMBER ( 사용자)
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'1','USER01','1234','새벽갬성','양종묵','KH01@KH.COM','01012341234','서울시강남구신사동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER02','1234','보마휘바','박미포','KH02@KH.COM','01023412341','서울시강남구논현동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER03','1234','후바후바','최미범','KH03@KH.COM','01034123412','서울시강남구역삼동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER04','1234','빵빵크림빵','이덕진','KH04@KH.COM','01041234123','서울시강남구논현동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'5','USER05','1234','고뿡빵','이덕범','KH05@KH.COM','01022342234','서울시강남구삼성동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'9','USER06','1234','히히잉힝','최광진','KH06@KH.COM','01013341334','서울시강남구개포동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'6','USER07','1234','체리맛민트','최현범','KH07@KH.COM','01013441344','서울시강남구대치동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NICK,NAME,EMAIL,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER08','1234','냉동파이리','양미우','KH08@KH.COM','01013451345','서울시강남구역삼동');
COMMIT;

--NOTICE (공지사항) 현묵님
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓을 소개합니다','<Cherry마켓 >은 중고거래 플랫폼입니다. 사용자들에게 물품 의 재활용을 촉진하고 소비를 장려하는 역할을 합니다. 회원분들의 편의를 위해 더욱 노력하는 Cherry마켓이 되겠습니다. 많은 이용 부탁드립니다. ');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 개인정보처리방치','모든 회원의 개인정보는 안전하게 저장되고 탈퇴 시 1년 후 개인정보가 삭제됩니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 휴먼계정 공지','저희 Cherry마켓은 회원님들의 소중한 개인정보 보호를 위하여 정보통신망 이용촉진 및 정보보호 등에 관한 법률에 따라 최근 1년 동안 이용 기록이 없는 회원은 휴면상태로 전환 됩니다 ');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 앱 출시','곧 Cherry마켓 스마트폰 앱이 출시 됩니다. 안드로이드 버전 아이폰 버전 둘 다 출시 예정입니다. 많은 관심 부탁드립니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'담배(전자담배) 거래시 계정 영구정지','저희 Cherry마켓은 전체 이용가이기 때문에 미성년자분들도 거래를 할 수 있어 담배(전자담배용품), 주류등은 거래하실 수 없습니다.');
INSERT INTO NOTICE(NOTICE_NO,MANAGER_NO,TITLE,CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL,1,'Cherry마켓 서버 점검 안내(10/31~)','안녕하세요 Cherry마켓입니다.보다 안정적인 서비스를 제공하기 위해 내부 서버 점검이 진행되어 공지드립니다. 점검 시간- 8/17(목) AM 6:00~AM 10:00 서비스 이용에 불편을 드려 죄송합니다. 더욱 더 안정적인 서비스 제공으로 보답하겠습니다.');

--FAQ 광포님
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '동네인증이 안 돼요!', '동네인증을 하기 전에 내 위치가 인증하려는 동네에 있는지 확인해주세요');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '가입한 적 없는데 계정이 있다고 나와요', '가입한 적이 없는데 계정이 있다고해서 많이 놀라셨죠?');
INSERT INTO FAQ(FAQ_NO, MANAGER_NO, TITLE, CONTENT) VALUES(SEQ_FAQ_NO.NEXTVAL, 1, '탈퇴는 어떻게 하나요?', '[나의 체리 > 오른쪽 위 톱니바퀴 모양 > 탈퇴하기]로 진행하시면 됩니다.');

--QNA (유저가 작성한 질문글)
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 5, '게시글 개수에 제한이 있나요?', '판매하고 싶은 제품이 많은데 게시글을 몇개 작성할 수 있는지 궁금합니다.');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 3, '택배 거래도 가능한가요?', '판매자가 회사에 판매물품을 두고와서 직거래가 어렵다고 택배로 거래하자는데 가능할까요?');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 7, '내 게시글이 안보여요.', '판매글을 작성했는데 게시글이 안보입니다.');
COMMIT;

--QNA (관리자가 작성한 답글)
UPDATE QNA SET ANSWER = '하루에 20개의 게시글을 작성 할 수 있고, 한 사람당 300개의 게시글을 작성할 수 있습니다.' WHERE QNA_NO = 1;
UPDATE QNA SET ANSWER = '택배 거래는 가능합니다. 다만 택배거래는 항상 사기 위험이 있으니 유의하시길 바랍니다.' WHERE QNA_NO = 2;
UPDATE QNA SET ANSWER = '중복게시글을 작성하셨거나 전문판매없자 제재를 받은 경우 게시글이 안보일 수 있습니다.' WHERE QNA_NO = 3;
COMMIT;

--TRADE
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 1, '노트북 팝니다', '역삼역 3번출구', '제곧내', 'M2맥북', 1000000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 2, 5, 'HTML 책 팝니다', '강남역 4번출구', 'The World Wide Web (W3) initiative links related information throughout the globe. HTML provides one simple format for providing linked information, and all W3 compatible programs are required to be capable of handling HTML. W3 uses an Internet protocol (Hypertext Transfer Protocol, HTTP), which allows transfer representations to be negotiated between client and server, the result being returned in an extended MIME message. HTML is therefore just one, but an important one, of the representations used with W3.', '도서', 10000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 3, 2, '세탁물 찾아주실분', 'KH세탁소', '제곧내', '...', 5000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 4, 3, '에어팟 팝니다', '수서역 앞', '에어팟 프로(Apple AirPods Pro)는 애플이 제조한 무선 이어폰으로, 2019년에 출시되었습니다. 에어팟 프로는 기존의 에어팟과 비교해 높은 음질, 주변 소음 차단, 햅틱 터치 컨트롤, 그리고 물리적으로 귀에 더 잘 맞는 디자인을 특징으로 합니다.', '에어팟프로', 50000);
INSERT INTO TRADE (BOARD_NO, MEMBER_NO, AREAS_CODE, TITLE, TRADE_AREAS, CONTENT, PRODUCT, PRICE)
VALUES (SEQ_BOARD_NO.NEXTVAL, 5, 6, '김치 팝니다', '우리집 앞', '김치는 대표적인 한국 요리로서 발효된 양배추나 다른 채소를 주로 고추가루와 다양한 조미료와 함께 발효시켜 만든 발효 식품입니다. 김치는 한국 요리의 중요한 부분이며 한국의 식탁에서 빠질 수 없는 음식 중 하나입니다.', '김치', 5000);
COMMIT;

--WISHLIST
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 3, 1);
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 2, 3);
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 3, 2);
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 5, 1);
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 4, 5);
INSERT INTO WISHLIST (WISHLIST_NO, BOARD_NO, MEMBER_NO) VALUES (SEQ_WISHLIST_NO.NEXTVAL, 4, 3);
COMMIT;

--PURCHASE_HISTORY (구매내역)
INSERT INTO PURCHASE_HISTORY (PURCHASE_NO, BUYER_NO, BOARD_NO) VALUES (SEQ_PURCHASE_NO.NEXTVAL, 1, 1);
INSERT INTO PURCHASE_HISTORY (PURCHASE_NO, BUYER_NO, BOARD_NO) VALUES (SEQ_PURCHASE_NO.NEXTVAL, 2, 2);
INSERT INTO PURCHASE_HISTORY (PURCHASE_NO, BUYER_NO, BOARD_NO) VALUES (SEQ_PURCHASE_NO.NEXTVAL, 4, 3);
INSERT INTO PURCHASE_HISTORY (PURCHASE_NO, BUYER_NO, BOARD_NO) VALUES (SEQ_PURCHASE_NO.NEXTVAL, 4, 4);
INSERT INTO PURCHASE_HISTORY (PURCHASE_NO, BUYER_NO, BOARD_NO) VALUES (SEQ_PURCHASE_NO.NEXTVAL, 3, 5);

--TOWN (동네생활)
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,1,'강아지를 찾습니다.','보시면 연락 주세요..ㅜ','자유게시판');
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,2,'지갑 찾아가세요~','공원에서 지갑을 주웠습니다!!!!','자유게시판' );
INSERT INTO TOWN(TOWN_NO, MEMBER_NO, TITLE, CONTENT, CATEGORY) VALUES (SEQ_TOWN_NO.NEXTVAL,3, '단기알바구합니다.', '하루4시간하실분찾아요...', '알바');
COMMIT;

--TOWN_COMMENT (동네생활 댓글)
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 1,1,'저희강아지같아요ㅜㅜㅜ');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 2,2,'어디로가면될까요!!!!');
INSERT INTO TOWN_COMMENT (COMMENT_NO, TOWN_NO, MEMBER_NO, CONTENT) VALUES (SEQ_TOWN_COMMENT_NO.NEXTVAL, 1,3,'시급은얼마인가요?');

--REVIEW (맨 밑으로 빼기)
INSERT INTO REVIEW (REVIEW_NO, PURCHASE_NO, SCORE, CONTENT) VALUES (SEQ_REVIEW_NO.NEXTVAL, 1, 1, '쿨거래 감사합니다');
INSERT INTO REVIEW (REVIEW_NO, PURCHASE_NO, SCORE, CONTENT) VALUES (SEQ_REVIEW_NO.NEXTVAL, 2, 1, '싸게 팔아주심');
INSERT INTO REVIEW (REVIEW_NO, PURCHASE_NO, SCORE, CONTENT) VALUES (SEQ_REVIEW_NO.NEXTVAL, 3, -1, '쓰레기를 팔았어요');
COMMIT;
