--테이블 삭제 구문
DROP TABLE MEMBER CASCADE CONSTRAINTS; --제약조건도 같이 삭제
DROP TABLE AREAS CASCADE CONSTRAINTS;  --제약조건도 같이 삭제
DROP TABLE MANAGER CASCADE CONSTRAINTS;  --제약조건도 같이 삭제

---------------------MEMBER---------------------
CREATE TABLE MEMBER (
	MEMBER_NO	    NUMBER		        PRIMARY KEY
	,AREAS_CODE	    NUMBER		        NOT NULL
	,ID	            VARCHAR2(100)		NOT NULL    UNIQUE
	,PWD	        VARCHAR2(100)		NOT NULL
	,NAME	        VARCHAR2(10)		NOT NULL   
	,EMALE	        VARCHAR2(100)		NOT NULL    UNIQUE
	,PHONE	        CHAR(12)		    NOT NULL    UNIQUE
	,ADDRESS	    VARCHAR2(100)		NOT NULL
	,JOIN_DATE	    TIMESTAMP	        DEFAULT SYSDATE
	,EDIT_DATE	    TIMESTAMP		    
	,QUIT_YN	    CHAR(1)	            DEFAULT 'N'	CHECK(QUIT_YN IN ('Y','N'))
);

---------------------코멘트--------------------
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '사용자번호';
COMMENT ON COLUMN "MEMBER"."AREAS_CODE" IS '동네번호';
COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';
COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."NAME" IS '사용자명';
COMMENT ON COLUMN "MEMBER"."EMALE" IS '이메일';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."JOIN_DATE" IS '가입일자';
COMMENT ON COLUMN "MEMBER"."EDIT_DATE" IS '마지막수정일자';
COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '탈퇴여부';
--시퀀스 생성
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;
--SEQ_MEMBER.NEXTVAL;
COMMIT;
---------------------AREAS---------------------
CREATE TABLE AREAS (
	AREAS_CODE	    NUMBER		 PRIMARY KEY
	,AREAS_NAME	    VARCHAR2(100) NOT NULL
);

---------------------코멘트--------------------
COMMENT ON COLUMN "AREAS"."AREAS_CODE" IS '동네번호';
COMMENT ON COLUMN "AREAS"."AREAS_NAME" IS '동네이름';

--시퀀스 생성
DROP SEQUENCE SEQ_AREAS;
CREATE SEQUENCE SEQ_AREAS NOCYCLE NOCACHE;
--SEQ_AREAS.NEXTVAL;
COMMIT;
---------------------MANAGER---------------------
CREATE TABLE MANAGER (
	MANAGER_NO	    NUMBER		    PRIMARY KEY
	,MANAGER_ID	    VARCHAR2(100)	NOT NULL    UNIQUE
	,PWD	        VARCHAR2(100)	NOT NULL
	,NAME	        VARCHAR2(100)	NOT NULL
	,JOIN_DATE	    TIMESTAMP	    DEFAULT SYSDATE
	,QUIT_YN	    CHAR(1)	        DEFAULT 'N' CHECK(QUIT_YN IN ('Y','N')) 
);
---------------------코멘트--------------------
COMMENT ON COLUMN "MANAGER"."MANAGER_NO" IS '관리자번호';
COMMENT ON COLUMN "MANAGER"."MANAGER_ID" IS '관리자아이디';
COMMENT ON COLUMN "MANAGER"."PWD" IS '비밀번호';
COMMENT ON COLUMN "MANAGER"."NAME" IS '관리자명';
COMMENT ON COLUMN "MANAGER"."JOIN_DATE" IS '가입일자';
COMMENT ON COLUMN "MANAGER"."QUIT_YN" IS '탈퇴여부';

--시퀀스 생성
DROP SEQUENCE SEQ_MANAGER;
CREATE SEQUENCE SEQ_MANAGER NOCYCLE NOCACHE;
--SEQ_MANAGER.NEXTVAL;
COMMIT;
-------------------외래키----------------------
ALTER TABLE MEMBER 
ADD CONSTRAINT FK_AREAS_MEMBER
FOREIGN KEY (AREAS_CODE) REFERENCES AREAS(AREAS_CODE);
COMMIT;


--더미데이터
--AREAS
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'신사동');--1
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'논현동');--2
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'압구정동');--3
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'청담동');--4
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'삼성동');--5
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'대치동');--6
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'삼성동');--7
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'역삼동');--8
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'개포동');--9
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'세곡동');--10
INSERT INTO AREAS(AREAS_CODE,AREAS_NAME) VALUES (SEQ_AREAS.NEXTVAL,'수서동');--11
COMMIT;
--MANAGER
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN01','1234','관리자01');
INSERT INTO MANAGER(MANAGER_NO,MANAGER_ID,PWD,NAME) VALUES (SEQ_MANAGER.NEXTVAL,'ADMIN02','1234','관리자02');
COMMIT;

--USER
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'1','USER01','1234','유저01','KH01@KH.COM','01012341234','서울시강남구역삼동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER02','1234','유저02','KH02@KH.COM','01023412341','서울시강남구논현동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER03','1234','유저03','KH03@KH.COM','01034123412','서울시강남구역삼동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'2','USER04','1234','유저04','KH04@KH.COM','01041234123','서울시강남구논현동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'5','USER05','1234','유저05','KH05@KH.COM','01022342234','서울시강남구삼성동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'9','USER06','1234','유저06','KH06@KH.COM','01013341334','서울시강남구개포동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'6','USER07','1234','유저07','KH07@KH.COM','01013441344','서울시강남구대치동');
INSERT INTO MEMBER(MEMBER_NO,AREAS_CODE,ID,PWD,NAME,EMALE,PHONE,ADDRESS) VALUES (SEQ_MEMBER.NEXTVAL,'8','USER08','1234','유저08','KH08@KH.COM','01013451345','서울시강남구역삼동');
COMMIT;

